version: "3.7"
services:
  vision:
    build:
      context: ./.docker
    container_name: vision
    ports:
      # Local port: docker port
      - 9000:8080 # Frontend
      - 3000:3000 # Backend
    volumes:
      - .:/opt/project

    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bildungsplattform

  db:
    image: mariadb
    ports:
        - 3306:3306
  adminer:
    image: adminer
    ports:
      # Local port: docker port
      - 8000:8080

